export const experiences = [
  {
    id: "alpixn",
    company: "Alpixn Technologies Private Limited",
    role: "Frontend Developer Intern",
    type: "Internship",
    startDate: "JUL 2025",
    endDate: "AUG 2025",
    location: "Remote",
    certificate: "/certificates/Alpixn_Certificate.png",
    current: false,
    bullets: [
      "Converted 15+ Figma designs into responsive, pixel-perfect UIs using React.js and Tailwind CSS.",
      "Ensured smooth data flow, quick UI updates, and seamless user interactions by integrating 10+ REST APIs.",
      "Built production-ready modules with optimized layouts, dark mode, and improved SEO structure, reducing UI issues by 20% through collaboration with senior developers.",
    ],
    techStack: ["React", "Tailwind", "APIs", "Figma"],
  },
  {
    id: "hivie",
    company: "Hivie Systems Private Limited",
    role: "Software Developer Intern",
    type: "Internship",
    startDate: "MAY 2025",
    endDate: "JULY 2025",
    location: "Remote",
    certificate: "/certificates/Anubhav_Hivie.png", 
    current: false,
    bullets: [
      "Shaped 20+ modern, responsive interfaces from detailed Figma designs using Next.js, Tailwind CSS, Magic UI, and TypeScript, following advanced UI/UX standards.",
      "Enhanced performance by memoizing data, optimizing render cycles to reduce latency by nearly 25%.",
      "Collaborated with backend to integrate APIs smoothly, ensuring reliable data flow and consistent user experience.",
      "Supported backend development by building and enhancing 5+ REST API endpoints with Express.js.",
    ],
    techStack: ["Next.js", "Redux Toolkit", "Axios", "Figma", "REST APIs", "Magic UI"],
  },
  {
    id: "shiphere",
    company: "Transportix Solutions Technology PVT LTD",
    role: "React Developer Intern",
    type: "Internship",
    startDate: "DEC 2024",
    endDate: "FEB 2025",
    location: "Remote",
    certificate: "/certificates/ShipHere.png", 
    current: false,
    bullets: [
      "Enhanced a partially developed client-facing web application by refactoring UI components and ensuring full responsiveness across multiple devices and screen sizes.",
      "Diagnosed and resolved API integration issues, improving data consistency and reducing runtime errors in key user workflows.",
      "Collaborated using Ant Design to standardize design patterns, optimize layouts, and deliver a more stable and production-ready user experience.",
    ],
    techStack: ["React", "ANT Design", "Tailwind CSS", "Axios", "Figma", "REST APIs"],
  },
];