export const projects = [
  {
    id: "carapp",
    title: "CarFusion",
    subtitle: "AI Powered Car Management App",
    description:
      "A full-stack car management platform that enables users to explore, filter, and analyze vehicle listings through interactive dashboards, role-based access for admins and users, and AI-powered vehicle information extraction using Google Gemini API from uploaded images.",
    techStack: [
      "Next.js",
      "Gemini API",
      "MongoDB",
      "Tailwind CSS",
      "shadcn/ui",
      "Cloudinary",
      "Vercel",
    ],
    githubUrl: "https://github.com/anubhav-0004/CarFusion",
    liveUrl: "https://car-fusion-ten.vercel.app/",
    featured: true,
    category: "fullstack",
    highlights: [
      "Role-based car marketplace with advanced search & filtering",
      "Test drive booking, wishlist management & secure Clerk authentication",
      "Admin analytics dashboard with vehicle, user & booking management",
    ],
  },
  {
    id: "chatapp",
    title: "Sandesh",
    subtitle: "Real-Time Chat Application",
    description:
      "A full-stack real-time chat platform featuring secure JWT authentication with role-based access, media sharing via Cloudinary, and high-performance Socket.IO messaging with optimized backend APIs for faster response times.",
    techStack: [
      "React.js",
      "Redux Toolkit",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "Socket.IO",
      "MongoDB",
      "JWT",
      "Multer",
      "Cloudinary",
    ],
    githubUrl: "https://github.com/anubhav-0004/ChatApp_frontend",
    liveUrl: "https://chat-app-frontend-indol-eight.vercel.app/",
    featured: false,
    category: "fullstack",
    icon: "💬",
  },
  {
    id: "groww",
    title: "FinBoard",
    subtitle: "Customizable Financial Dashboard",
    description:
      "A production-ready financial analytics dashboard enabling dynamic widget management, real-time market data visualization, and secure multi-API integration with drag-and-drop layouts, smart symbol search, and global theme persistence.",
    techStack: [
      "Next.js",
      "Tailwind CSS",
      "Redux Toolkit",
      "Chart.js",
      "@dnd-kit",
      "Finnhub API",
      "Alpha Vantage API",
    ],
    githubUrl: "https://github.com/anubhav-0004/Groww__Assignment",
    liveUrl: "https://groww-assignment-gray.vercel.app/",
    featured: false,
    category: "frontend",
    icon: "📊",
  },
  {
    id: "blogapp",
    title: "Blog Website",
    subtitle: "Full-Stack Blogging Platform",
    description:
      "A full-stack blog application enabling secure authentication, CRUD operations for personal blogs, public blog exploration, and local image uploads with a responsive Tailwind-based UI and robust Express-MySQL backend.",
    techStack: [
      "React.js",
      "Tailwind CSS",
      "Express.js",
      "MySQL",
      "JWT",
      "Axios",
      "React Router",
      "Multer",
    ],
    githubUrl: "https://github.com/anubhav-0004/Blog_App",
    liveUrl: "https://blog-app-red-nine.vercel.app/",
    featured: false,
    category: "fullstack",
    icon: "🤖",
  },
];
